"""TEMPORARY on-disk store used when S3 refuses an upload.

-- Why this exists ------------------------------------------------------------------------
Every upload in the ERP goes through `s3_service.upload_file_to_s3_with_key`. When the AWS
credential is dead or the bucket is unreachable, that call raises and the caller turns it
into a 503 -- which, on the public job-application form, means the candidate loses a filled
form at the final step. This module lets the write land on local disk instead, so the form
keeps working through an outage or a key rotation.

-- It is a FALLBACK, not a storage backend -------------------------------------------------
S3 is tried first, always. This is reached only when S3 has already failed, and only when
`LOCAL_UPLOAD_FALLBACK` is switched on. The moment S3 works again, new uploads go back to
S3 with no further change -- there is no mode to get stuck in.

-- What it costs ---------------------------------------------------------------------------
Files written here are personal data (CVs, ID documents) sitting on one server's filesystem:
not replicated, probably not backed up, and gone if the box is rebuilt. Treat anything under
`local/` as owed a trip to S3. `scripts/migrate_local_uploads_to_s3.py` does that, and
`--report` counts what is outstanding.

-- The key format is the whole trick --------------------------------------------------------
A stored key looks like `local/<uuid>_<name>`. Callers persist keys, not URLs, so the prefix
travels with the record: `get_signed_url` sees it and serves from disk, the migration script
finds every affected record with one query, and a human reading the database can tell at a
glance which files are not in S3 yet.

-- Access control ----------------------------------------------------------------------------
Reads mirror S3 presigning rather than inventing a weaker rule: a URL carries an expiry and
an HMAC over `key|expiry` keyed on SECRET_KEY, and the serving route (routes/local_files.py)
recomputes it. Possession of an unexpired URL grants the file, exactly as with S3 -- so a
caller that was safe handing out a presigned URL is equally safe here.
"""
from __future__ import annotations

import hashlib
import hmac
import os
import time
import uuid
from typing import Optional, Tuple

from app.config.settings import settings

# The one prefix that marks a key as living on local disk rather than in S3.
LOCAL_KEY_PREFIX = "local/"


def is_enabled() -> bool:
    return bool(settings.LOCAL_UPLOAD_FALLBACK)


def is_local_key(key: Optional[str]) -> bool:
    return bool(key) and str(key).startswith(LOCAL_KEY_PREFIX)


def storage_root() -> str:
    """Absolute path of the upload directory, resolved against the backend package root so
    it does not move with the process's working directory."""
    configured = settings.LOCAL_UPLOAD_DIR or "var/uploads"
    if os.path.isabs(configured):
        return configured
    backend_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    return os.path.join(backend_root, configured)


def _disk_path(key: str) -> str:
    """Map a `local/...` key to a path INSIDE the storage root.

    The stored name is generated by this module (a uuid plus an already-sanitised filename),
    but this is the function that turns a database value into a filesystem path, so it
    re-checks rather than trusts: the resolved path must sit under the root, which stops a
    key doctored to contain `..` from reaching anything else on the disk.
    """
    relative = str(key)[len(LOCAL_KEY_PREFIX):]
    root = os.path.realpath(storage_root())
    resolved = os.path.realpath(os.path.join(root, relative))
    if resolved != root and not resolved.startswith(root + os.sep):
        raise ValueError(f"Refusing a local key that escapes the storage root: {key!r}")
    return resolved


def store(file_obj, filename: str, content_type: str) -> dict:
    """Write one file to disk and return the same shape `upload_file_to_s3_with_key` does.

    Raises on failure. The caller is already inside S3's failure path, so a failure here
    means both stores are unavailable and the request genuinely cannot be served.
    """
    root = storage_root()
    os.makedirs(root, exist_ok=True)

    stored_name = f"{uuid.uuid4()}_{filename}"
    key = f"{LOCAL_KEY_PREFIX}{stored_name}"
    path = _disk_path(key)

    try:
        file_obj.seek(0)
    except Exception:
        pass                                    # a plain bytes buffer may not be seekable
    with open(path, "wb") as handle:
        handle.write(file_obj.read())

    # WARNING, not INFO: this is a degraded path and the operator needs to know it is being
    # taken. A silent fallback becomes permanent, which is exactly the outcome to avoid.
    print(f"[WARN] S3 unavailable - stored upload on local disk instead: {key} "
          f"({content_type}). Migrate with scripts/migrate_local_uploads_to_s3.py")
    return {"key": key, "url": signed_url(key), "local": True}


def signed_url(key: str, expires_in: Optional[int] = None) -> str:
    """A time-limited URL for a locally-stored file, mirroring an S3 presigned URL."""
    ttl = expires_in or settings.LOCAL_UPLOAD_URL_TTL_SECONDS or 3600
    expiry = int(time.time()) + int(ttl)
    return f"/api/files/local?key={key}&expires={expiry}&signature={_sign(key, expiry)}"


def _sign(key: str, expiry: int) -> str:
    secret = (settings.SECRET_KEY or "").encode("utf-8")
    message = f"{key}|{expiry}".encode("utf-8")
    return hmac.new(secret, message, hashlib.sha256).hexdigest()


def verify(key: str, expiry: str, signature: str) -> Tuple[bool, str]:
    """Check a signed link. Returns (ok, reason) -- the reason is for the server log, never
    for the response, since telling a caller which half of a link was wrong helps only
    somebody guessing at them."""
    if not is_local_key(key):
        return False, "not a local key"
    try:
        expiry_ts = int(expiry)
    except (TypeError, ValueError):
        return False, "malformed expiry"
    if expiry_ts < int(time.time()):
        return False, "expired"
    # compare_digest: the comparison must not leak, through its timing, how much of a
    # candidate signature was correct.
    if not hmac.compare_digest(_sign(key, expiry_ts), str(signature or "")):
        return False, "bad signature"
    return True, ""


def read(key: str) -> bytes:
    with open(_disk_path(key), "rb") as handle:
        return handle.read()


def exists(key: str) -> bool:
    try:
        return os.path.isfile(_disk_path(key))
    except ValueError:
        return False


def delete(key: str) -> bool:
    """Remove a local file. Used by the migration script once S3 holds the copy."""
    try:
        path = _disk_path(key)
    except ValueError:
        return False
    try:
        os.remove(path)
        return True
    except FileNotFoundError:
        return True                             # already gone is the outcome we wanted
    except OSError as e:
        print(f"[WARN] could not delete local upload {key}: {e}")
        return False
